# Generated by Django 5.0.1 on 2024-01-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
