# Generated by Django 5.0.1 on 2024-02-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_favoriteproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные товары'},
        ),
    ]
